version: 0.2

env:
  parameter-store:
    DB_SERVER_PARAM: '/api/$NODE_ENV/db-url'
    DB_USER_PARAM: '/api/$NODE_ENV/db-username'
    DB_PASSWORD_PARAM: '/api/$NODE_ENV/db-password'
    API_SECRET_PARAM: '/api/$NODE_ENV/jwt-secret'

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=527574042611.dkr.ecr.ca-central-1.amazonaws.com/api-scorecard
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $REPOSITORY_URI
      - ENV_TAG=$NODE_ENV

      #- docker build -t $REPOSITORY_URI:latest .
      - docker build -t $REPOSITORY_URI:latest . --build-arg NODE_ENV=${NODE_ENV} --build-arg API_SECRET=${API_SECRET_PARAM} --build-arg DB_SERVER=${DB_SERVER_PARAM} --build-arg DB_USER=${DB_USER_PARAM} --build-arg DB_PASSWORD=${DB_PASSWORD_PARAM}
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$ENV_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$ENV_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"api-scorecard","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
